<script lang="ts">
  import { T, Var } from "better-translation/svelte";

  let { data } = $props();

  const name = "Jack";
  const date = formatExampleDate(new Date());

  function formatExampleDate(date: Date) {
    return date.toISOString().slice(0, 10);
  }

  async function handleLocaleChange(event: Event) {
    const locale = (event.currentTarget as HTMLSelectElement).value;
    const body = new FormData();
    body.set("locale", locale);

    const response = await fetch("?/setLocale", {
      method: "POST",
      body,
    });

    if (response.ok) window.location.reload();
  }
</script>

<main class="page">
  <label class="locale-field">
    <T>Locale</T>
    <select
      aria-label="Select locale"
      value={data.locale}
      onchange={handleLocaleChange}
    >
      {#each data.locales as locale}
        <option value={locale}>{locale.toUpperCase()}</option>
      {/each}
    </select>
  </label>

  <h1>
    <T>Hello there!</T>
  </h1>

  <p>
    <T context="A welcome greeting to the user, be super friendly.">
      Welcome <Var {name} />, the date is <Var {date} />!
    </T>
  </p>

  <p>
    <T>
      This SvelteKit example uses local Runtime bundles generated by the Vite
      plugin.
    </T>
  </p>
</main>
