/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/app/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppAccountLayoutRouteImport } from './routes/app/account/layout'
import { Route as AppOrgSlugLayoutRouteImport } from './routes/app/$orgSlug/layout'
import { Route as AppCreateOrgIndexRouteImport } from './routes/app/create-org/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as ApiGithubWebhooksRouteImport } from './routes/api/github/webhooks'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppOrgSlugOrgLayoutRouteImport } from './routes/app/$orgSlug/_org/layout'
import { Route as AppAccountAuthenticationIndexRouteImport } from './routes/app/account/authentication/index'
import { Route as AppOrgSlugOrgIndexRouteImport } from './routes/app/$orgSlug/_org/index'
import { Route as AppOrgSlugProjectsProjectSlugLayoutRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/layout'
import { Route as AppOrgSlugProjectsProjectSlugIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/index'
import { Route as AppOrgSlugOrgUsersIndexRouteImport } from './routes/app/$orgSlug/_org/users/index'
import { Route as AppOrgSlugOrgSettingsIndexRouteImport } from './routes/app/$orgSlug/_org/settings/index'
import { Route as AppOrgSlugOrgNewIndexRouteImport } from './routes/app/$orgSlug/_org/new/index'
import { Route as AppOrgSlugProjectsProjectSlugTranslatorIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/translator/index'
import { Route as AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/settings/index'
import { Route as AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/branches/index'
import { Route as AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/api-keys/index'
import { Route as AppOrgSlugProjectsProjectSlugBranchNameIndexRouteImport } from './routes/app/$orgSlug/_projects/$projectSlug/$branchName/index'
import { Route as ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport } from './routes/projects/$projectId/branches/$branchName/locales/{$locale}[.]json'
import { Route as ApiProjectsProjectIdBranchesBranchNameManifestRouteImport } from './routes/api/projects/$projectId/branches/$branchName/manifest'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppAccountLayoutRoute = AppAccountLayoutRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSlugLayoutRoute = AppOrgSlugLayoutRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCreateOrgIndexRoute = AppCreateOrgIndexRouteImport.update({
  id: '/create-org/',
  path: '/create-org/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountLayoutRoute,
} as any)
const ApiGithubWebhooksRoute = ApiGithubWebhooksRouteImport.update({
  id: '/api/github/webhooks',
  path: '/api/github/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugOrgLayoutRoute = AppOrgSlugOrgLayoutRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppAccountAuthenticationIndexRoute =
  AppAccountAuthenticationIndexRouteImport.update({
    id: '/authentication/',
    path: '/authentication/',
    getParentRoute: () => AppAccountLayoutRoute,
  } as any)
const AppOrgSlugOrgIndexRoute = AppOrgSlugOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugOrgLayoutRoute,
} as any)
const AppOrgSlugProjectsProjectSlugLayoutRoute =
  AppOrgSlugProjectsProjectSlugLayoutRouteImport.update({
    id: '/_projects/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => AppOrgSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugIndexRoute =
  AppOrgSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugOrgUsersIndexRoute = AppOrgSlugOrgUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppOrgSlugOrgLayoutRoute,
} as any)
const AppOrgSlugOrgSettingsIndexRoute =
  AppOrgSlugOrgSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugOrgLayoutRoute,
  } as any)
const AppOrgSlugOrgNewIndexRoute = AppOrgSlugOrgNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AppOrgSlugOrgLayoutRoute,
} as any)
const AppOrgSlugProjectsProjectSlugTranslatorIndexRoute =
  AppOrgSlugProjectsProjectSlugTranslatorIndexRouteImport.update({
    id: '/translator/',
    path: '/translator/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugSettingsIndexRoute =
  AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugBranchesIndexRoute =
  AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugApiKeysIndexRoute =
  AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugBranchNameIndexRoute =
  AppOrgSlugProjectsProjectSlugBranchNameIndexRouteImport.update({
    id: '/$branchName/',
    path: '/$branchName/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute =
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport.update(
    {
      id: '/projects/$projectId/branches/$branchName/locales/{$locale}.json',
      path: '/projects/$projectId/branches/$branchName/locales/{$locale}.json',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiProjectsProjectIdBranchesBranchNameManifestRoute =
  ApiProjectsProjectIdBranchesBranchNameManifestRouteImport.update({
    id: '/api/projects/$projectId/branches/$branchName/manifest',
    path: '/api/projects/$projectId/branches/$branchName/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/app/account': typeof AppAccountLayoutRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhooks': typeof ApiGithubWebhooksRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/create-org/': typeof AppCreateOrgIndexRoute
  '/app/$orgSlug/$projectSlug': typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
  '/app/$orgSlug/': typeof AppOrgSlugOrgIndexRoute
  '/app/account/authentication/': typeof AppAccountAuthenticationIndexRoute
  '/app/$orgSlug/new/': typeof AppOrgSlugOrgNewIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/users/': typeof AppOrgSlugOrgUsersIndexRoute
  '/app/$orgSlug/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/$projectSlug/$branchName/': typeof AppOrgSlugProjectsProjectSlugBranchNameIndexRoute
  '/app/$orgSlug/$projectSlug/api-keys/': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/$projectSlug/branches/': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/$projectSlug/settings/': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/$projectSlug/translator/': typeof AppOrgSlugProjectsProjectSlugTranslatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$orgSlug': typeof AppOrgSlugOrgIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhooks': typeof ApiGithubWebhooksRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/create-org': typeof AppCreateOrgIndexRoute
  '/app/account/authentication': typeof AppAccountAuthenticationIndexRoute
  '/app/$orgSlug/new': typeof AppOrgSlugOrgNewIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/users': typeof AppOrgSlugOrgUsersIndexRoute
  '/app/$orgSlug/$projectSlug': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/$projectSlug/$branchName': typeof AppOrgSlugProjectsProjectSlugBranchNameIndexRoute
  '/app/$orgSlug/$projectSlug/api-keys': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/$projectSlug/branches': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/$projectSlug/settings': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/$projectSlug/translator': typeof AppOrgSlugProjectsProjectSlugTranslatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/app': typeof AppLayoutRouteWithChildren
  '/app/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/app/account': typeof AppAccountLayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/$orgSlug/_org': typeof AppOrgSlugOrgLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhooks': typeof ApiGithubWebhooksRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/create-org/': typeof AppCreateOrgIndexRoute
  '/app/$orgSlug/_projects/$projectSlug': typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
  '/app/$orgSlug/_org/': typeof AppOrgSlugOrgIndexRoute
  '/app/account/authentication/': typeof AppAccountAuthenticationIndexRoute
  '/app/$orgSlug/_org/new/': typeof AppOrgSlugOrgNewIndexRoute
  '/app/$orgSlug/_org/settings/': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/_org/users/': typeof AppOrgSlugOrgUsersIndexRoute
  '/app/$orgSlug/_projects/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/_projects/$projectSlug/$branchName/': typeof AppOrgSlugProjectsProjectSlugBranchNameIndexRoute
  '/app/$orgSlug/_projects/$projectSlug/api-keys/': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/_projects/$projectSlug/branches/': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/_projects/$projectSlug/settings/': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/_projects/$projectSlug/translator/': typeof AppOrgSlugProjectsProjectSlugTranslatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$orgSlug'
    | '/app/account'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/app/'
    | '/docs/'
    | '/api/auth/$'
    | '/api/github/setup'
    | '/api/github/webhooks'
    | '/app/account/'
    | '/app/create-org/'
    | '/app/$orgSlug/$projectSlug'
    | '/app/$orgSlug/'
    | '/app/account/authentication/'
    | '/app/$orgSlug/new/'
    | '/app/$orgSlug/settings/'
    | '/app/$orgSlug/users/'
    | '/app/$orgSlug/$projectSlug/'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/$projectSlug/$branchName/'
    | '/app/$orgSlug/$projectSlug/api-keys/'
    | '/app/$orgSlug/$projectSlug/branches/'
    | '/app/$orgSlug/$projectSlug/settings/'
    | '/app/$orgSlug/$projectSlug/translator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/app'
    | '/docs'
    | '/api/auth/$'
    | '/api/github/setup'
    | '/api/github/webhooks'
    | '/app/account'
    | '/app/create-org'
    | '/app/account/authentication'
    | '/app/$orgSlug/new'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/users'
    | '/app/$orgSlug/$projectSlug'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/$projectSlug/$branchName'
    | '/app/$orgSlug/$projectSlug/api-keys'
    | '/app/$orgSlug/$projectSlug/branches'
    | '/app/$orgSlug/$projectSlug/settings'
    | '/app/$orgSlug/$projectSlug/translator'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/app/$orgSlug'
    | '/app/account'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/app/'
    | '/docs/'
    | '/app/$orgSlug/_org'
    | '/api/auth/$'
    | '/api/github/setup'
    | '/api/github/webhooks'
    | '/app/account/'
    | '/app/create-org/'
    | '/app/$orgSlug/_projects/$projectSlug'
    | '/app/$orgSlug/_org/'
    | '/app/account/authentication/'
    | '/app/$orgSlug/_org/new/'
    | '/app/$orgSlug/_org/settings/'
    | '/app/$orgSlug/_org/users/'
    | '/app/$orgSlug/_projects/$projectSlug/'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/_projects/$projectSlug/$branchName/'
    | '/app/$orgSlug/_projects/$projectSlug/api-keys/'
    | '/app/$orgSlug/_projects/$projectSlug/branches/'
    | '/app/$orgSlug/_projects/$projectSlug/settings/'
    | '/app/$orgSlug/_projects/$projectSlug/translator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhooksRoute: typeof ApiGithubWebhooksRoute
  ApiProjectsProjectIdBranchesBranchNameManifestRoute: typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute: typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/create-org/': {
      id: '/app/create-org/'
      path: '/create-org'
      fullPath: '/app/create-org/'
      preLoaderRoute: typeof AppCreateOrgIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountLayoutRoute
    }
    '/api/github/webhooks': {
      id: '/api/github/webhooks'
      path: '/api/github/webhooks'
      fullPath: '/api/github/webhooks'
      preLoaderRoute: typeof ApiGithubWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/_org': {
      id: '/app/$orgSlug/_org'
      path: ''
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugOrgLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    '/app/account/authentication/': {
      id: '/app/account/authentication/'
      path: '/authentication'
      fullPath: '/app/account/authentication/'
      preLoaderRoute: typeof AppAccountAuthenticationIndexRouteImport
      parentRoute: typeof AppAccountLayoutRoute
    }
    '/app/$orgSlug/_org/': {
      id: '/app/$orgSlug/_org/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugOrgIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug': {
      id: '/app/$orgSlug/_projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/app/$orgSlug/$projectSlug'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/': {
      id: '/app/$orgSlug/_projects/$projectSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/$projectSlug/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_org/users/': {
      id: '/app/$orgSlug/_org/users/'
      path: '/users'
      fullPath: '/app/$orgSlug/users/'
      preLoaderRoute: typeof AppOrgSlugOrgUsersIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_org/settings/': {
      id: '/app/$orgSlug/_org/settings/'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugOrgSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_org/new/': {
      id: '/app/$orgSlug/_org/new/'
      path: '/new'
      fullPath: '/app/$orgSlug/new/'
      preLoaderRoute: typeof AppOrgSlugOrgNewIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/translator/': {
      id: '/app/$orgSlug/_projects/$projectSlug/translator/'
      path: '/translator'
      fullPath: '/app/$orgSlug/$projectSlug/translator/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugTranslatorIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/settings/': {
      id: '/app/$orgSlug/_projects/$projectSlug/settings/'
      path: '/settings'
      fullPath: '/app/$orgSlug/$projectSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/branches/': {
      id: '/app/$orgSlug/_projects/$projectSlug/branches/'
      path: '/branches'
      fullPath: '/app/$orgSlug/$projectSlug/branches/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/api-keys/': {
      id: '/app/$orgSlug/_projects/$projectSlug/api-keys/'
      path: '/api-keys'
      fullPath: '/app/$orgSlug/$projectSlug/api-keys/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_projects/$projectSlug/$branchName/': {
      id: '/app/$orgSlug/_projects/$projectSlug/$branchName/'
      path: '/$branchName'
      fullPath: '/app/$orgSlug/$projectSlug/$branchName/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugBranchNameIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/projects/$projectId/branches/$branchName/locales/{$locale}.json': {
      id: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      path: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      fullPath: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      preLoaderRoute: typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/branches/$branchName/manifest': {
      id: '/api/projects/$projectId/branches/$branchName/manifest'
      path: '/api/projects/$projectId/branches/$branchName/manifest'
      fullPath: '/api/projects/$projectId/branches/$branchName/manifest'
      preLoaderRoute: typeof ApiProjectsProjectIdBranchesBranchNameManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AppOrgSlugOrgLayoutRouteChildren {
  AppOrgSlugOrgIndexRoute: typeof AppOrgSlugOrgIndexRoute
  AppOrgSlugOrgNewIndexRoute: typeof AppOrgSlugOrgNewIndexRoute
  AppOrgSlugOrgSettingsIndexRoute: typeof AppOrgSlugOrgSettingsIndexRoute
  AppOrgSlugOrgUsersIndexRoute: typeof AppOrgSlugOrgUsersIndexRoute
}

const AppOrgSlugOrgLayoutRouteChildren: AppOrgSlugOrgLayoutRouteChildren = {
  AppOrgSlugOrgIndexRoute: AppOrgSlugOrgIndexRoute,
  AppOrgSlugOrgNewIndexRoute: AppOrgSlugOrgNewIndexRoute,
  AppOrgSlugOrgSettingsIndexRoute: AppOrgSlugOrgSettingsIndexRoute,
  AppOrgSlugOrgUsersIndexRoute: AppOrgSlugOrgUsersIndexRoute,
}

const AppOrgSlugOrgLayoutRouteWithChildren =
  AppOrgSlugOrgLayoutRoute._addFileChildren(AppOrgSlugOrgLayoutRouteChildren)

interface AppOrgSlugProjectsProjectSlugLayoutRouteChildren {
  AppOrgSlugProjectsProjectSlugIndexRoute: typeof AppOrgSlugProjectsProjectSlugIndexRoute
  AppOrgSlugProjectsProjectSlugBranchNameIndexRoute: typeof AppOrgSlugProjectsProjectSlugBranchNameIndexRoute
  AppOrgSlugProjectsProjectSlugApiKeysIndexRoute: typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  AppOrgSlugProjectsProjectSlugBranchesIndexRoute: typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  AppOrgSlugProjectsProjectSlugSettingsIndexRoute: typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  AppOrgSlugProjectsProjectSlugTranslatorIndexRoute: typeof AppOrgSlugProjectsProjectSlugTranslatorIndexRoute
}

const AppOrgSlugProjectsProjectSlugLayoutRouteChildren: AppOrgSlugProjectsProjectSlugLayoutRouteChildren =
  {
    AppOrgSlugProjectsProjectSlugIndexRoute:
      AppOrgSlugProjectsProjectSlugIndexRoute,
    AppOrgSlugProjectsProjectSlugBranchNameIndexRoute:
      AppOrgSlugProjectsProjectSlugBranchNameIndexRoute,
    AppOrgSlugProjectsProjectSlugApiKeysIndexRoute:
      AppOrgSlugProjectsProjectSlugApiKeysIndexRoute,
    AppOrgSlugProjectsProjectSlugBranchesIndexRoute:
      AppOrgSlugProjectsProjectSlugBranchesIndexRoute,
    AppOrgSlugProjectsProjectSlugSettingsIndexRoute:
      AppOrgSlugProjectsProjectSlugSettingsIndexRoute,
    AppOrgSlugProjectsProjectSlugTranslatorIndexRoute:
      AppOrgSlugProjectsProjectSlugTranslatorIndexRoute,
  }

const AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren =
  AppOrgSlugProjectsProjectSlugLayoutRoute._addFileChildren(
    AppOrgSlugProjectsProjectSlugLayoutRouteChildren,
  )

interface AppOrgSlugLayoutRouteChildren {
  AppOrgSlugOrgLayoutRoute: typeof AppOrgSlugOrgLayoutRouteWithChildren
  AppOrgSlugProjectsProjectSlugLayoutRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
}

const AppOrgSlugLayoutRouteChildren: AppOrgSlugLayoutRouteChildren = {
  AppOrgSlugOrgLayoutRoute: AppOrgSlugOrgLayoutRouteWithChildren,
  AppOrgSlugProjectsProjectSlugLayoutRoute:
    AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren,
}

const AppOrgSlugLayoutRouteWithChildren =
  AppOrgSlugLayoutRoute._addFileChildren(AppOrgSlugLayoutRouteChildren)

interface AppAccountLayoutRouteChildren {
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAccountAuthenticationIndexRoute: typeof AppAccountAuthenticationIndexRoute
}

const AppAccountLayoutRouteChildren: AppAccountLayoutRouteChildren = {
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAccountAuthenticationIndexRoute: AppAccountAuthenticationIndexRoute,
}

const AppAccountLayoutRouteWithChildren =
  AppAccountLayoutRoute._addFileChildren(AppAccountLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppOrgSlugLayoutRoute: typeof AppOrgSlugLayoutRouteWithChildren
  AppAccountLayoutRoute: typeof AppAccountLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCreateOrgIndexRoute: typeof AppCreateOrgIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppOrgSlugLayoutRoute: AppOrgSlugLayoutRouteWithChildren,
  AppAccountLayoutRoute: AppAccountLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCreateOrgIndexRoute: AppCreateOrgIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiUploadRoute: ApiUploadRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhooksRoute: ApiGithubWebhooksRoute,
  ApiProjectsProjectIdBranchesBranchNameManifestRoute:
    ApiProjectsProjectIdBranchesBranchNameManifestRoute,
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute:
    ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
