/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppOrgSlugLayoutRouteImport } from './routes/app/$orgSlug/layout'
import { Route as AppCreateOrgIndexRouteImport } from './routes/app/create-org/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppOrgSlugOrgLayoutRouteImport } from './routes/app/$orgSlug/_org/layout'
import { Route as AppOrgSlugOrgIndexRouteImport } from './routes/app/$orgSlug/_org/index'
import { Route as AppOrgSlugOrgUsersRouteImport } from './routes/app/$orgSlug/_org/users'
import { Route as AppOrgSlugProjectsProjectSlugLayoutRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/layout'
import { Route as AppOrgSlugProjectsProjectSlugIndexRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/index'
import { Route as AppOrgSlugOrgSettingsIndexRouteImport } from './routes/app/$orgSlug/_org/settings/index'
import { Route as AppOrgSlugOrgProjectsIndexRouteImport } from './routes/app/$orgSlug/_org/projects/index'
import { Route as AppOrgSlugOrgProjectsNewRouteImport } from './routes/app/$orgSlug/_org/projects/new'
import { Route as AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/settings/index'
import { Route as AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/branches/index'
import { Route as AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/api-keys/index'
import { Route as ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport } from './routes/projects/$projectId/branches/$branchName/locales/{$locale}[.]json'
import { Route as ApiProjectsProjectIdBranchesBranchNameManifestRouteImport } from './routes/api/projects/$projectId/branches/$branchName/manifest'
import { Route as AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRouteImport } from './routes/app/$orgSlug/projects/$projectSlug/branches/$branchName/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppOrgSlugLayoutRoute = AppOrgSlugLayoutRouteImport.update({
  id: '/app/$orgSlug',
  path: '/app/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateOrgIndexRoute = AppCreateOrgIndexRouteImport.update({
  id: '/app/create-org/',
  path: '/app/create-org/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugOrgLayoutRoute = AppOrgSlugOrgLayoutRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugOrgIndexRoute = AppOrgSlugOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugOrgLayoutRoute,
} as any)
const AppOrgSlugOrgUsersRoute = AppOrgSlugOrgUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppOrgSlugOrgLayoutRoute,
} as any)
const AppOrgSlugProjectsProjectSlugLayoutRoute =
  AppOrgSlugProjectsProjectSlugLayoutRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AppOrgSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugIndexRoute =
  AppOrgSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugOrgSettingsIndexRoute =
  AppOrgSlugOrgSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugOrgLayoutRoute,
  } as any)
const AppOrgSlugOrgProjectsIndexRoute =
  AppOrgSlugOrgProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppOrgSlugOrgLayoutRoute,
  } as any)
const AppOrgSlugOrgProjectsNewRoute =
  AppOrgSlugOrgProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AppOrgSlugOrgLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugSettingsIndexRoute =
  AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugBranchesIndexRoute =
  AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugApiKeysIndexRoute =
  AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)
const ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute =
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport.update(
    {
      id: '/projects/$projectId/branches/$branchName/locales/{$locale}.json',
      path: '/projects/$projectId/branches/$branchName/locales/{$locale}.json',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiProjectsProjectIdBranchesBranchNameManifestRoute =
  ApiProjectsProjectIdBranchesBranchNameManifestRouteImport.update({
    id: '/api/projects/$projectId/branches/$branchName/manifest',
    path: '/api/projects/$projectId/branches/$branchName/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute =
  AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRouteImport.update({
    id: '/branches/$branchName/',
    path: '/branches/$branchName/',
    getParentRoute: () => AppOrgSlugProjectsProjectSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/create-org/': typeof AppCreateOrgIndexRoute
  '/app/$orgSlug/projects/$projectSlug': typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
  '/app/$orgSlug/users': typeof AppOrgSlugOrgUsersRoute
  '/app/$orgSlug/': typeof AppOrgSlugOrgIndexRoute
  '/app/$orgSlug/projects/new': typeof AppOrgSlugOrgProjectsNewRoute
  '/app/$orgSlug/projects/': typeof AppOrgSlugOrgProjectsIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/projects/$projectSlug/api-keys/': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches/': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/projects/$projectSlug/settings/': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches/$branchName/': typeof AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$orgSlug': typeof AppOrgSlugOrgIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/create-org': typeof AppCreateOrgIndexRoute
  '/app/$orgSlug/users': typeof AppOrgSlugOrgUsersRoute
  '/app/$orgSlug/projects/new': typeof AppOrgSlugOrgProjectsNewRoute
  '/app/$orgSlug/projects': typeof AppOrgSlugOrgProjectsIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/projects/$projectSlug/api-keys': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/projects/$projectSlug/settings': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches/$branchName': typeof AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/app/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/_org': typeof AppOrgSlugOrgLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/create-org/': typeof AppCreateOrgIndexRoute
  '/app/$orgSlug/projects/$projectSlug': typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
  '/app/$orgSlug/_org/users': typeof AppOrgSlugOrgUsersRoute
  '/app/$orgSlug/_org/': typeof AppOrgSlugOrgIndexRoute
  '/app/$orgSlug/_org/projects/new': typeof AppOrgSlugOrgProjectsNewRoute
  '/app/$orgSlug/_org/projects/': typeof AppOrgSlugOrgProjectsIndexRoute
  '/app/$orgSlug/_org/settings/': typeof AppOrgSlugOrgSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
  '/api/projects/$projectId/branches/$branchName/manifest': typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  '/projects/$projectId/branches/$branchName/locales/{$locale}.json': typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
  '/app/$orgSlug/projects/$projectSlug/api-keys/': typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches/': typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  '/app/$orgSlug/projects/$projectSlug/settings/': typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/branches/$branchName/': typeof AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/app/'
    | '/api/auth/$'
    | '/app/create-org/'
    | '/app/$orgSlug/projects/$projectSlug'
    | '/app/$orgSlug/users'
    | '/app/$orgSlug/'
    | '/app/$orgSlug/projects/new'
    | '/app/$orgSlug/projects/'
    | '/app/$orgSlug/settings/'
    | '/app/$orgSlug/projects/$projectSlug/'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/projects/$projectSlug/api-keys/'
    | '/app/$orgSlug/projects/$projectSlug/branches/'
    | '/app/$orgSlug/projects/$projectSlug/settings/'
    | '/app/$orgSlug/projects/$projectSlug/branches/$branchName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$orgSlug'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/app'
    | '/api/auth/$'
    | '/app/create-org'
    | '/app/$orgSlug/users'
    | '/app/$orgSlug/projects/new'
    | '/app/$orgSlug/projects'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/projects/$projectSlug'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/projects/$projectSlug/api-keys'
    | '/app/$orgSlug/projects/$projectSlug/branches'
    | '/app/$orgSlug/projects/$projectSlug/settings'
    | '/app/$orgSlug/projects/$projectSlug/branches/$branchName'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app/$orgSlug'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/accept-invitation/$invitationId'
    | '/app/'
    | '/app/$orgSlug/_org'
    | '/api/auth/$'
    | '/app/create-org/'
    | '/app/$orgSlug/projects/$projectSlug'
    | '/app/$orgSlug/_org/users'
    | '/app/$orgSlug/_org/'
    | '/app/$orgSlug/_org/projects/new'
    | '/app/$orgSlug/_org/projects/'
    | '/app/$orgSlug/_org/settings/'
    | '/app/$orgSlug/projects/$projectSlug/'
    | '/api/projects/$projectId/branches/$branchName/manifest'
    | '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
    | '/app/$orgSlug/projects/$projectSlug/api-keys/'
    | '/app/$orgSlug/projects/$projectSlug/branches/'
    | '/app/$orgSlug/projects/$projectSlug/settings/'
    | '/app/$orgSlug/projects/$projectSlug/branches/$branchName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AppOrgSlugLayoutRoute: typeof AppOrgSlugLayoutRouteWithChildren
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppCreateOrgIndexRoute: typeof AppCreateOrgIndexRoute
  ApiProjectsProjectIdBranchesBranchNameManifestRoute: typeof ApiProjectsProjectIdBranchesBranchNameManifestRoute
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute: typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/app/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create-org/': {
      id: '/app/create-org/'
      path: '/app/create-org'
      fullPath: '/app/create-org/'
      preLoaderRoute: typeof AppCreateOrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/_org': {
      id: '/app/$orgSlug/_org'
      path: ''
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugOrgLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    '/app/$orgSlug/_org/': {
      id: '/app/$orgSlug/_org/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugOrgIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_org/users': {
      id: '/app/$orgSlug/_org/users'
      path: '/users'
      fullPath: '/app/$orgSlug/users'
      preLoaderRoute: typeof AppOrgSlugOrgUsersRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/projects/$projectSlug': {
      id: '/app/$orgSlug/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/app/$orgSlug/projects/$projectSlug'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    '/app/$orgSlug/projects/$projectSlug/': {
      id: '/app/$orgSlug/projects/$projectSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/_org/settings/': {
      id: '/app/$orgSlug/_org/settings/'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugOrgSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_org/projects/': {
      id: '/app/$orgSlug/_org/projects/'
      path: '/projects'
      fullPath: '/app/$orgSlug/projects/'
      preLoaderRoute: typeof AppOrgSlugOrgProjectsIndexRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/_org/projects/new': {
      id: '/app/$orgSlug/_org/projects/new'
      path: '/projects/new'
      fullPath: '/app/$orgSlug/projects/new'
      preLoaderRoute: typeof AppOrgSlugOrgProjectsNewRouteImport
      parentRoute: typeof AppOrgSlugOrgLayoutRoute
    }
    '/app/$orgSlug/projects/$projectSlug/settings/': {
      id: '/app/$orgSlug/projects/$projectSlug/settings/'
      path: '/settings'
      fullPath: '/app/$orgSlug/projects/$projectSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/projects/$projectSlug/branches/': {
      id: '/app/$orgSlug/projects/$projectSlug/branches/'
      path: '/branches'
      fullPath: '/app/$orgSlug/projects/$projectSlug/branches/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugBranchesIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/app/$orgSlug/projects/$projectSlug/api-keys/': {
      id: '/app/$orgSlug/projects/$projectSlug/api-keys/'
      path: '/api-keys'
      fullPath: '/app/$orgSlug/projects/$projectSlug/api-keys/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
    '/projects/$projectId/branches/$branchName/locales/{$locale}.json': {
      id: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      path: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      fullPath: '/projects/$projectId/branches/$branchName/locales/{$locale}.json'
      preLoaderRoute: typeof ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/branches/$branchName/manifest': {
      id: '/api/projects/$projectId/branches/$branchName/manifest'
      path: '/api/projects/$projectId/branches/$branchName/manifest'
      fullPath: '/api/projects/$projectId/branches/$branchName/manifest'
      preLoaderRoute: typeof ApiProjectsProjectIdBranchesBranchNameManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/projects/$projectSlug/branches/$branchName/': {
      id: '/app/$orgSlug/projects/$projectSlug/branches/$branchName/'
      path: '/branches/$branchName'
      fullPath: '/app/$orgSlug/projects/$projectSlug/branches/$branchName/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AppOrgSlugOrgLayoutRouteChildren {
  AppOrgSlugOrgUsersRoute: typeof AppOrgSlugOrgUsersRoute
  AppOrgSlugOrgIndexRoute: typeof AppOrgSlugOrgIndexRoute
  AppOrgSlugOrgProjectsNewRoute: typeof AppOrgSlugOrgProjectsNewRoute
  AppOrgSlugOrgProjectsIndexRoute: typeof AppOrgSlugOrgProjectsIndexRoute
  AppOrgSlugOrgSettingsIndexRoute: typeof AppOrgSlugOrgSettingsIndexRoute
}

const AppOrgSlugOrgLayoutRouteChildren: AppOrgSlugOrgLayoutRouteChildren = {
  AppOrgSlugOrgUsersRoute: AppOrgSlugOrgUsersRoute,
  AppOrgSlugOrgIndexRoute: AppOrgSlugOrgIndexRoute,
  AppOrgSlugOrgProjectsNewRoute: AppOrgSlugOrgProjectsNewRoute,
  AppOrgSlugOrgProjectsIndexRoute: AppOrgSlugOrgProjectsIndexRoute,
  AppOrgSlugOrgSettingsIndexRoute: AppOrgSlugOrgSettingsIndexRoute,
}

const AppOrgSlugOrgLayoutRouteWithChildren =
  AppOrgSlugOrgLayoutRoute._addFileChildren(AppOrgSlugOrgLayoutRouteChildren)

interface AppOrgSlugProjectsProjectSlugLayoutRouteChildren {
  AppOrgSlugProjectsProjectSlugIndexRoute: typeof AppOrgSlugProjectsProjectSlugIndexRoute
  AppOrgSlugProjectsProjectSlugApiKeysIndexRoute: typeof AppOrgSlugProjectsProjectSlugApiKeysIndexRoute
  AppOrgSlugProjectsProjectSlugBranchesIndexRoute: typeof AppOrgSlugProjectsProjectSlugBranchesIndexRoute
  AppOrgSlugProjectsProjectSlugSettingsIndexRoute: typeof AppOrgSlugProjectsProjectSlugSettingsIndexRoute
  AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute: typeof AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute
}

const AppOrgSlugProjectsProjectSlugLayoutRouteChildren: AppOrgSlugProjectsProjectSlugLayoutRouteChildren =
  {
    AppOrgSlugProjectsProjectSlugIndexRoute:
      AppOrgSlugProjectsProjectSlugIndexRoute,
    AppOrgSlugProjectsProjectSlugApiKeysIndexRoute:
      AppOrgSlugProjectsProjectSlugApiKeysIndexRoute,
    AppOrgSlugProjectsProjectSlugBranchesIndexRoute:
      AppOrgSlugProjectsProjectSlugBranchesIndexRoute,
    AppOrgSlugProjectsProjectSlugSettingsIndexRoute:
      AppOrgSlugProjectsProjectSlugSettingsIndexRoute,
    AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute:
      AppOrgSlugProjectsProjectSlugBranchesBranchNameIndexRoute,
  }

const AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren =
  AppOrgSlugProjectsProjectSlugLayoutRoute._addFileChildren(
    AppOrgSlugProjectsProjectSlugLayoutRouteChildren,
  )

interface AppOrgSlugLayoutRouteChildren {
  AppOrgSlugOrgLayoutRoute: typeof AppOrgSlugOrgLayoutRouteWithChildren
  AppOrgSlugProjectsProjectSlugLayoutRoute: typeof AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren
}

const AppOrgSlugLayoutRouteChildren: AppOrgSlugLayoutRouteChildren = {
  AppOrgSlugOrgLayoutRoute: AppOrgSlugOrgLayoutRouteWithChildren,
  AppOrgSlugProjectsProjectSlugLayoutRoute:
    AppOrgSlugProjectsProjectSlugLayoutRouteWithChildren,
}

const AppOrgSlugLayoutRouteWithChildren =
  AppOrgSlugLayoutRoute._addFileChildren(AppOrgSlugLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AppOrgSlugLayoutRoute: AppOrgSlugLayoutRouteWithChildren,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppCreateOrgIndexRoute: AppCreateOrgIndexRoute,
  ApiProjectsProjectIdBranchesBranchNameManifestRoute:
    ApiProjectsProjectIdBranchesBranchNameManifestRoute,
  ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute:
    ProjectsProjectIdBranchesBranchNameLocalesChar123localeChar125DotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
