import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, relative, resolve } from "node:path"
import type { Plugin } from "vite"

import type {
  BetterTranslatePluginOptions,
  BetterTranslateRuntimeConfig,
  ExtractedMessage,
  ManifestEntry,
  MessageManifest,
  MessageManifestFile,
  MessageSource,
  RuntimeMessages,
  TranslateMessage,
  TranslationCache,
} from "./types.js"

import { createEmptyCache, getCacheKey, loadCache, saveCache } from "./cache.js"
import { analyzeSourceFile } from "./extractor.js"
import { serializeMeta } from "./message-id.js"
import { DEFAULT_LOCAL_OUTPUT_DIR, getRuntimeConfigPath } from "./runtime-config.js"

const PREFIX = "\x1b[36m[better-translation]\x1b[0m"
const DIM = "\x1b[2m"
const RESET = "\x1b[0m"
const YELLOW = "\x1b[33m"
const BOLD = "\x1b[1m"
const CYAN = "\x1b[36m"
const HOSTED_API_BASE_URL = "https://better-translate.com"
const HOSTED_STUB = `${YELLOW}stub${RESET}`
const DEFAULT_SCAN_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"]
const PRIVATE_MANIFEST_FILENAME = "manifest.json"
const LOAD_MESSAGES_FILENAME = "load-messages.ts"
const LOCALES_SUBDIR = "locales"
const GITIGNORE_FILENAME = ".gitignore"
const GITIGNORE_CONTENTS = ["# Generated by @better-translate/vite", "manifest.json", ""].join("\n")

function formatLocale(locale: string) {
  return locale.toUpperCase()
}

function formatLocales(locales: string[]) {
  return locales.map(formatLocale).join(", ")
}

/** Scans source files for translatable messages and keeps locale JSON files in sync. */
export function betterTranslate(options: BetterTranslatePluginOptions): Plugin {
  const {
    locales,
    defaultLocale = locales[0] ?? "en",
    cacheFile = ".cache/better-translate.json",
    logging = true,
    scan,
    storage = { type: "local", dir: "locales" },
    markers = {},
    translate,
  } = options
  const usesLocalStorage = storage.type === "local"
  const localesDir = storage.type === "local" ? (storage.dir ?? DEFAULT_LOCAL_OUTPUT_DIR) : DEFAULT_LOCAL_OUTPUT_DIR
  const hostedUrl = storage.type === "hosted" ? (storage.url ?? HOSTED_API_BASE_URL) : HOSTED_API_BASE_URL

  const callMarkers = markers.call ?? ["t", "useT"]
  const componentMarkers = markers.component ?? ["T"]
  const taggedTemplateMarkers = markers.taggedTemplate ?? ["msg"]
  const manifest: MessageManifest = {}
  const fileMessages = new Map<string, ExtractedMessage[]>()
  let cache: TranslationCache = createEmptyCache()
  let root = ""
  let isDev = false
  let translateTimer: ReturnType<typeof setTimeout> | null = null
  let warnedHostedTranslateStub = false
  let warnedHostedSyncStub = false
  let scanRoots: string[] = []
  let scanExtensions: string[] = []

  function log(message: string) {
    if (logging) console.log(message)
  }

  async function hostedTranslate(messages: TranslateMessage[], _locale: string) {
    if (!warnedHostedTranslateStub) {
      warnedHostedTranslateStub = true
      log(`${PREFIX} ${HOSTED_STUB} hosted translate via ${DIM}${hostedUrl}${RESET} not implemented yet`)
    }
    return Object.fromEntries(messages.map((message) => [message.id, message.text])) as Record<string, string>
  }

  async function syncHosted() {
    if (!warnedHostedSyncStub) {
      warnedHostedSyncStub = true
      log(`${PREFIX} ${HOSTED_STUB} hosted locale sync via ${DIM}${hostedUrl}${RESET} not implemented yet`)
    }
  }

  const resolvedTranslate = translate ?? (usesLocalStorage ? undefined : hostedTranslate)

  function buildRuntimeMessages(locale: string): RuntimeMessages {
    const messages: RuntimeMessages = {}
    for (const [id, entry] of Object.entries(manifest)) {
      messages[id] =
        locale === defaultLocale
          ? entry.defaultMessage
          : (cache.entries[getCacheKey(id, locale)]?.translation ?? entry.defaultMessage)
    }
    return messages
  }

  function buildMessageManifest(): MessageManifestFile {
    return Object.fromEntries(
      Object.entries(manifest).map(([id, entry]) => [
        id,
        {
          defaultMessage: entry.defaultMessage,
          meta: entry.meta,
          placeholders: entry.placeholders,
          sources: entry.sources,
        },
      ]),
    )
  }

  function shouldScanFile(id: string) {
    const cleanId = id.split("?", 1)[0] ?? id
    if (cleanId.includes("node_modules")) return false
    const extension = scanExtensions.find((ext) => cleanId.endsWith(ext))
    if (!extension) return false
    return scanRoots.some((scanRoot) => cleanId.startsWith(scanRoot))
  }

  function getPrivateManifestPath() {
    return resolve(root, localesDir, PRIVATE_MANIFEST_FILENAME)
  }

  function getRuntimeConfig(): BetterTranslateRuntimeConfig {
    return {
      storage: usesLocalStorage ? { type: "local", dir: localesDir } : { type: "hosted", url: hostedUrl },
      defaultLocale,
      locales,
    }
  }

  function writeRuntimeConfig() {
    if (!usesLocalStorage) return

    const runtimeConfig = JSON.stringify(getRuntimeConfig(), null, 2) + "\n"
    const path = getRuntimeConfigPath(root, localesDir)
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(path, runtimeConfig)
  }

  function getLocalesDirPath() {
    return resolve(root, localesDir, LOCALES_SUBDIR)
  }

  function getLocalePath(locale: string) {
    return resolve(getLocalesDirPath(), `${locale}.json`)
  }

  function readLocaleMessages(locale: string): RuntimeMessages {
    const path = getLocalePath(locale)
    if (!existsSync(path)) return {}

    try {
      const input = JSON.parse(readFileSync(path, "utf-8")) as unknown
      return normalizeLocaleMessages(input)
    } catch {
      return {}
    }
  }

  function writePrivateManifest() {
    if (!usesLocalStorage) return
    const path = getPrivateManifestPath()
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(path, JSON.stringify(buildMessageManifest(), null, 2) + "\n")
  }

  function buildLoadMessagesModule() {
    const localeUnion = locales.map((locale) => JSON.stringify(locale)).join(" | ")
    const importLines = locales.map((locale) => `import messages_${locale} from "./${LOCALES_SUBDIR}/${locale}.json"`)
    const caseLines = locales.map((locale) => `    case ${JSON.stringify(locale)}: return messages_${locale}`)
    return [
      ...importLines,
      "",
      `export type AppLocale = ${localeUnion}`,
      "",
      "export async function loadMessages(locale: AppLocale): Promise<Record<string, string>> {",
      "  switch (locale) {",
      ...caseLines,
      `    default: return messages_${defaultLocale}`,
      "  }",
      "}",
      "",
    ].join("\n")
  }

  function writeLoadMessagesModule() {
    if (!usesLocalStorage) return
    const path = resolve(root, localesDir, LOAD_MESSAGES_FILENAME)
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    const next = buildLoadMessagesModule()
    if (existsSync(path) && readFileSync(path, "utf-8") === next) return
    writeFileSync(path, next)
  }

  function writeGitignore() {
    if (!usesLocalStorage) return
    const path = resolve(root, localesDir, GITIGNORE_FILENAME)
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    if (existsSync(path) && readFileSync(path, "utf-8") === GITIGNORE_CONTENTS) return
    writeFileSync(path, GITIGNORE_CONTENTS)
  }

  function buildLocalLocaleMessages(locale: string): RuntimeMessages {
    if (locale === defaultLocale) return buildRuntimeMessages(locale)

    const existingMessages = readLocaleMessages(locale)
    const messages: RuntimeMessages = {}
    for (const id of Object.keys(manifest)) {
      const existingMessage = existingMessages[id]
      if (existingMessage) {
        messages[id] = existingMessage
        continue
      }

      const cachedMessage = cache.entries[getCacheKey(id, locale)]?.translation
      if (cachedMessage) messages[id] = cachedMessage
    }
    return messages
  }

  function writeLocaleFilesToDisk() {
    if (!usesLocalStorage) return
    const dir = getLocalesDirPath()
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    for (const locale of locales) {
      writeFileSync(resolve(dir, `${locale}.json`), JSON.stringify(buildLocalLocaleMessages(locale), null, 2) + "\n")
    }
    writeLoadMessagesModule()
  }

  function getMissingMessagesByLocale() {
    const missingByLocale = new Map<string, TranslateMessage[]>()

    for (const locale of locales) {
      if (locale === defaultLocale) continue
      const existingMessages = readLocaleMessages(locale)
      for (const [id, entry] of Object.entries(manifest)) {
        if (!existingMessages[id] && !cache.entries[getCacheKey(id, locale)]) {
          const misses = missingByLocale.get(locale) ?? []
          misses.push({
            id,
            text: entry.defaultMessage,
            meta: entry.meta,
            placeholders: entry.placeholders,
            sources: entry.sources,
          })
          missingByLocale.set(locale, misses)
        }
      }
    }

    return missingByLocale
  }

  function assertLocalBuildTranslationsComplete() {
    const missingByLocale = new Map<string, string[]>()
    for (const locale of locales) {
      if (locale === defaultLocale) continue
      const localeMessages = readLocaleMessages(locale)
      const missingIds = Object.keys(manifest).filter((id) => !localeMessages[id])
      if (missingIds.length > 0) missingByLocale.set(locale, missingIds)
    }
    const totalMissingIds = [...missingByLocale.values()].reduce((count, misses) => count + misses.length, 0)
    if (totalMissingIds === 0) return

    const summary = [...missingByLocale]
      .map(([locale, misses]) => {
        const preview = misses
          .slice(0, 5)
          .map((id) => `"${manifest[id]?.defaultMessage ?? id}"`)
          .join(", ")
        const suffix = misses.length > 5 ? `, ... ${misses.length - 5} more` : ""
        return `- ${locale}: ${misses.length} missing (${preview}${suffix})`
      })
      .join("\n")

    throw new Error(
      [
        `${PREFIX} missing committed locale JSON entries for local production build`,
        `local builds never call translate() during production builds`,
        `fill the locale JSON files in ${localesDir} and rebuild`,
        summary,
      ].join("\n"),
    )
  }

  async function translateMissingMessages() {
    if (!resolvedTranslate) return false
    const missingByLocale = getMissingMessagesByLocale()

    const totalMisses = [...missingByLocale.values()].reduce((count, misses) => count + misses.length, 0)
    if (totalMisses === 0) return false

    const missLocales = [...missingByLocale.keys()]
    log(
      `${PREFIX} ${BOLD}Translating${RESET} ${CYAN}${totalMisses}${RESET} ${totalMisses === 1 ? "Message" : "Messages"} -> ${CYAN}${formatLocales(missLocales)}${RESET}`,
    )

    for (const [locale, misses] of missingByLocale) {
      const result = await resolvedTranslate(misses, locale)

      for (const miss of misses) {
        const translated = result[miss.id] ?? miss.text
        cache.entries[getCacheKey(miss.id, locale)] = {
          sourceText: miss.text,
          meta: miss.meta,
          locale,
          translation: translated,
          timestamp: Date.now(),
        }
      }
    }

    return true
  }

  function scheduleDevTranslation() {
    if (!resolvedTranslate) return
    if (!isDev) return
    if (translateTimer) clearTimeout(translateTimer)
    translateTimer = setTimeout(async () => {
      const translated = await translateMissingMessages()
      if (translated) saveCache(resolve(root, cacheFile), cache)
      writeLocaleFilesToDisk()
      writePrivateManifest()
    }, 1000)
  }

  function removeFileMessages(file: string) {
    const previous = fileMessages.get(file)
    if (!previous) return false

    for (const message of previous) {
      const entry = manifest[message.id]
      if (!entry) continue
      entry.sources = entry.sources.filter((source) => !isSameSource(source, message.source))
      if (entry.sources.length === 0) delete manifest[message.id]
    }

    fileMessages.delete(file)
    return true
  }

  function syncFileMessages(file: string, messages: ExtractedMessage[]) {
    const nextEntries = groupMessagesById(messages)
    for (const [id, entry] of Object.entries(nextEntries)) {
      const existing = manifest[id]
      if (existing && !hasSameMessageShape(existing, entry)) {
        throw new Error(formatCollisionError(id, existing, entry))
      }
    }

    const hadPreviousMessages = removeFileMessages(file)
    for (const [id, entry] of Object.entries(nextEntries)) {
      if (!manifest[id]) {
        manifest[id] = entry
        continue
      }
      for (const source of entry.sources) {
        if (!manifest[id]!.sources.some((existingSource) => isSameSource(existingSource, source))) {
          manifest[id]!.sources.push(source)
        }
      }
    }

    if (messages.length > 0) fileMessages.set(file, messages)
    return hadPreviousMessages || messages.length > 0
  }

  function toRootRelativePath(file: string) {
    return relative(root, file).replaceAll("\\", "/")
  }

  return {
    name: "better-translate-extract",
    enforce: "pre",

    configResolved(config) {
      root = config.root
      isDev = config.command === "serve"
      scanRoots = (scan?.roots ?? ["src"]).map((scanRoot) => resolve(root, scanRoot))
      scanExtensions = scan?.extensions ?? DEFAULT_SCAN_EXTENSIONS
      log(
        `${PREFIX} Locales: ${CYAN}${formatLocales(locales)}${RESET} | Default: ${CYAN}${formatLocale(defaultLocale)}${RESET} | Storage: ${CYAN}${usesLocalStorage ? "Local" : "Hosted"}${RESET} | Out Dir: ${DIM}${usesLocalStorage ? localesDir : "n/a"}${RESET} | Scan: ${DIM}${(scan?.roots ?? ["src"]).join(", ")}${RESET}`,
      )
    },

    buildStart() {
      cache = loadCache(resolve(root, cacheFile))
      writeRuntimeConfig()
      writeLoadMessagesModule()
      writeGitignore()
      writePrivateManifest()
    },

    transform(code, id) {
      const cleanId = id.split("?", 1)[0] ?? id
      if (!shouldScanFile(cleanId)) return

      const analysis = analyzeSourceFile(code, cleanId, {
        call: callMarkers,
        component: componentMarkers,
        taggedTemplate: taggedTemplateMarkers,
        logging,
      })
      const manifestChanged = syncFileMessages(
        cleanId,
        analysis.messages.map((message) => ({
          ...message,
          source: {
            ...message.source,
            file: toRootRelativePath(message.source.file),
          },
        })),
      )

      if (manifestChanged && isDev) {
        writeLocaleFilesToDisk()
        writePrivateManifest()
        scheduleDevTranslation()
      }

      if (analysis.edits.length === 0) return
      return {
        code: applyEdits(code, analysis.edits),
        map: null,
      }
    },

    async generateBundle() {
      if (usesLocalStorage) {
        writeRuntimeConfig()
        assertLocalBuildTranslationsComplete()
      } else {
        await translateMissingMessages()
      }

      if (!usesLocalStorage) {
        await syncHosted()
      }
    },

    closeBundle() {
      saveCache(resolve(root, cacheFile), cache)
    },
  }
}

function normalizeLocaleMessages(input: unknown): RuntimeMessages {
  if (isRuntimeMessages(input)) return input
  if (
    typeof input === "object" &&
    input !== null &&
    "messages" in input &&
    typeof input.messages === "object" &&
    input.messages !== null
  ) {
    return Object.fromEntries(
      Object.entries(input.messages).flatMap(([id, entry]) =>
        typeof entry === "object" && entry !== null && "translation" in entry && typeof entry.translation === "string"
          ? [[id, entry.translation]]
          : [],
      ),
    ) as RuntimeMessages
  }
  return {}
}

function isRuntimeMessages(input: unknown): input is RuntimeMessages {
  return typeof input === "object" && input !== null && Object.values(input).every((value) => typeof value === "string")
}

function applyEdits(code: string, edits: Array<{ start: number; end: number; replacement: string }>) {
  let transformed = code
  for (const edit of [...edits].sort((a, b) => b.start - a.start)) {
    transformed = `${transformed.slice(0, edit.start)}${edit.replacement}${transformed.slice(edit.end)}`
  }
  return transformed
}

function groupMessagesById(messages: ExtractedMessage[]): MessageManifest {
  const grouped: MessageManifest = {}

  for (const message of messages) {
    const existing = grouped[message.id]
    if (existing && !hasSameMessageShape(existing, message)) {
      throw new Error(formatCollisionError(message.id, existing, message))
    }
    if (!existing) {
      grouped[message.id] = {
        defaultMessage: message.defaultMessage,
        meta: message.meta,
        placeholders: message.placeholders,
        sources: [message.source],
      }
      continue
    }
    if (!existing.sources.some((source) => isSameSource(source, message.source))) {
      existing.sources.push(message.source)
    }
  }

  return grouped
}

function hasSameMessageShape(
  existing: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders">,
  incoming: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders"> | ExtractedMessage,
) {
  return (
    existing.defaultMessage === incoming.defaultMessage &&
    serializeMeta(existing.meta) === serializeMeta(incoming.meta) &&
    JSON.stringify(existing.placeholders) === JSON.stringify(incoming.placeholders)
  )
}

function isSameSource(left: MessageSource, right: MessageSource) {
  return (
    left.file === right.file &&
    left.kind === right.kind &&
    left.marker === right.marker &&
    left.start === right.start &&
    left.end === right.end
  )
}

function formatCollisionError(
  id: string,
  existing: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders" | "sources">,
  incoming: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders" | "sources"> | ExtractedMessage,
) {
  const existingSources = formatSources(existing.sources)
  const incomingSources = formatSources("source" in incoming ? [incoming.source] : incoming.sources)
  return [
    `${PREFIX} conflicting message definition for ${BOLD}"${id}"${RESET}`,
    `existing: ${JSON.stringify({ defaultMessage: existing.defaultMessage, meta: existing.meta, placeholders: existing.placeholders })}`,
    `existing sources: ${existingSources}`,
    `incoming: ${JSON.stringify({ defaultMessage: incoming.defaultMessage, meta: incoming.meta, placeholders: incoming.placeholders })}`,
    `incoming sources: ${incomingSources}`,
  ].join("\n")
}

function formatSources(sources: MessageSource[]) {
  return sources.map((source) => `${source.file}:${source.line}:${source.column}`).join(", ")
}
