// Auto-generated by better-translation/vite - do not edit.
// Delete this file to regenerate from your plugin `locales` config.

export const locales = ["en", "nl"] as const

export type AppLocale = (typeof locales)[number]

export async function loadMessages(locale: AppLocale): Promise<Record<string, string>> {
  const messages = await import(`./locales/${locale}.json`)
  return messages.default
}
