// Auto-generated by better-translation/vite - do not edit.
// Delete this file to regenerate from your plugin `locales` config.

export type AppLocale = "en" | "nl" | "fr" | "es"

export async function loadMessages(locale: AppLocale): Promise<Record<string, string>> {
  const messages = await import(`./locales/${locale}.json`)
  return messages.default
}
