/**
 * Virtual Runtime bundle loader generated by the Better Translation Vite
 * plugin.
 *
 * @packageDocumentation
 */
import type { RuntimeMessages } from "./types.js"

export type { RuntimeMessages } from "./types.js"

/** Locale codes configured in the Vite plugin, in configuration order. */
export const locales: readonly string[] = []

/** A Locale accepted by {@link loadMessages}. */
export type Locale = string

/**
 * Loads the flat Runtime bundle for a configured Locale.
 *
 * The Vite plugin replaces this module with a loader for the configured local
 * or remote runtime. Unknown Locales and failed public or remote requests reject
 * the returned promise.
 *
 * @param locale - Configured Locale code to load.
 * @returns Locale values keyed by Lookup id.
 */
export async function loadMessages(_locale: string): Promise<RuntimeMessages> {
  throw new Error("better-translation/messages must be loaded through the Better Translation Vite plugin.")
}
