import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, relative, resolve } from "node:path"
import { normalizePath, type Plugin, type ResolvedConfig } from "vite"

import type {
  BetterTranslatePluginOptions,
  BetterTranslateRuntimeOptions,
  BetterTranslateStorageOptions,
  BetterTranslateRuntimeConfig,
  ExtractedMessage,
  ManifestEntry,
  MessageManifest,
  MessageManifestFile,
  MessageSource,
  RuntimeMessages,
  TranslateMessage,
  TranslationCache,
} from "./types.js"

import { createEmptyCache, getCacheKey, loadCache, saveCache } from "./cache.js"
import { analyzeSourceFile } from "./extractor.js"
import { serializeMeta } from "./message-id.js"
import {
  DEFAULT_LOCAL_OUTPUT_DIR,
  DEFAULT_PUBLIC_BASE_PATH,
  DEFAULT_PUBLIC_OUTPUT_SUBDIR,
  getRuntimeConfigPath,
} from "./runtime-config.js"

const PREFIX = "\x1b[36m[better-translation]\x1b[0m"
const DIM = "\x1b[2m"
const RESET = "\x1b[0m"
const YELLOW = "\x1b[33m"
const BOLD = "\x1b[1m"
const CYAN = "\x1b[36m"
const REMOTE_API_BASE_URL = "https://better-translation.com"
const REMOTE_STUB = `${YELLOW}stub${RESET}`
const DEFAULT_ROOT_DIR = "src"
const DEFAULT_SCAN_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"]
const VIRTUAL_MESSAGES_MODULE_ID = "better-translation/messages"
const RESOLVED_VIRTUAL_MESSAGES_MODULE_ID = `\0${VIRTUAL_MESSAGES_MODULE_ID}`
const CALL_MARKERS = ["t", "useT"]
const COMPONENT_MARKERS = ["T"]
const PRIVATE_MANIFEST_FILENAME = "manifest.json"
const LOCALES_SUBDIR = "locales"
const GITIGNORE_FILENAME = ".gitignore"
const GITIGNORE_CONTENTS = ["# Generated by better-translation/vite", "manifest.json", ""].join("\n")

interface SyncResult {
  manifestChanged: boolean
  localeMessagesChanged: boolean
}

function formatLocale(locale: string) {
  return locale.toUpperCase()
}

function formatLocales(locales: string[]) {
  return locales.map(formatLocale).join(", ")
}

/** Scans source files for translatable messages and keeps locale JSON files in sync. */
export function betterTranslation(options: BetterTranslatePluginOptions): Plugin {
  const {
    locales,
    defaultLocale = locales[0] ?? "en",
    rootDir = DEFAULT_ROOT_DIR,
    cacheFile = ".cache/better-translation.json",
    logging = true,
    runtime,
    storage,
    translate,
  } = options
  const configuredRuntime = normalizeRuntimeOptions(runtime, storage)
  const manifest: MessageManifest = {}
  const fileMessages = new Map<string, ExtractedMessage[]>()
  let cache: TranslationCache = createEmptyCache()
  let resolvedRuntime = configuredRuntime
  let usesLocalStorage = configuredRuntime.type === "local"
  let localesDir =
    configuredRuntime.type === "local" ? (configuredRuntime.output ?? DEFAULT_LOCAL_OUTPUT_DIR) : DEFAULT_LOCAL_OUTPUT_DIR
  let publicBasePath =
    configuredRuntime.type === "local" && configuredRuntime.target === "public"
      ? (configuredRuntime.basePath ?? DEFAULT_PUBLIC_BASE_PATH)
      : DEFAULT_PUBLIC_BASE_PATH
  let remoteUrl = configuredRuntime.type === "remote" ? (configuredRuntime.endpoint ?? REMOTE_API_BASE_URL) : REMOTE_API_BASE_URL
  let root = ""
  let isDev = false
  let translateTimer: ReturnType<typeof setTimeout> | null = null
  let warnedRemoteTranslateStub = false
  let warnedRemoteSyncStub = false
  let sourceRoots: string[] = []

  function log(message: string) {
    if (logging) console.log(message)
  }

  async function remoteTranslate(messages: TranslateMessage[], _locale: string) {
    if (!warnedRemoteTranslateStub) {
      warnedRemoteTranslateStub = true
      log(`${PREFIX} ${REMOTE_STUB} remote translate via ${DIM}${remoteUrl}${RESET} not implemented yet`)
    }
    return Object.fromEntries(messages.map((message) => [message.id, message.text])) as Record<string, string>
  }

  async function syncRemote() {
    if (!warnedRemoteSyncStub) {
      warnedRemoteSyncStub = true
      log(`${PREFIX} ${REMOTE_STUB} remote locale sync via ${DIM}${remoteUrl}${RESET} not implemented yet`)
    }
  }

  const resolvedTranslate = translate ?? (usesLocalStorage ? undefined : remoteTranslate)

  function buildMessageManifest(): MessageManifestFile {
    return Object.fromEntries(
      Object.entries(manifest).map(([id, entry]) => [
        id,
        {
          defaultMessage: entry.defaultMessage,
          meta: entry.meta,
          placeholders: entry.placeholders,
          sources: entry.sources,
        },
      ]),
    )
  }

  function shouldScanFile(id: string) {
    const cleanId = id.split("?", 1)[0] ?? id
    if (cleanId.includes("node_modules")) return false
    const extension = DEFAULT_SCAN_EXTENSIONS.find((ext) => cleanId.endsWith(ext))
    if (!extension) return false
    return sourceRoots.some(
      (sourceRoot) => cleanId === sourceRoot || cleanId.startsWith(`${sourceRoot}/`) || cleanId.startsWith(`${sourceRoot}\\`),
    )
  }

  function getPrivateManifestPath() {
    return resolve(root, localesDir, PRIVATE_MANIFEST_FILENAME)
  }

  function getRuntimeConfig(): BetterTranslateRuntimeConfig {
    return {
      runtime: resolvedRuntime,
      defaultLocale,
      locales,
    }
  }

  function writeRuntimeConfig() {
    if (!usesLocalStorage) return

    const runtimeConfig = JSON.stringify(getRuntimeConfig(), null, 2) + "\n"
    const path = getRuntimeConfigPath(root, localesDir)
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileIfChanged(path, runtimeConfig)
  }

  function getLocalesDirPath() {
    return resolve(root, localesDir, LOCALES_SUBDIR)
  }

  function getLocalePath(locale: string) {
    return resolve(getLocalesDirPath(), `${locale}.json`)
  }

  function readLocaleMessages(locale: string): RuntimeMessages {
    const path = getLocalePath(locale)
    if (!existsSync(path)) return {}

    try {
      const input = JSON.parse(readFileSync(path, "utf-8")) as unknown
      return normalizeLocaleMessages(input)
    } catch {
      return {}
    }
  }

  function writePrivateManifest() {
    if (!usesLocalStorage) return
    const path = getPrivateManifestPath()
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileIfChanged(path, JSON.stringify(buildMessageManifest(), null, 2) + "\n")
  }

  function assertFileContents(path: string, expected: string, label: string) {
    if (!existsSync(path)) {
      throw new Error(`${PREFIX} missing committed ${label} at ${relative(root, path)}`)
    }
    const actual = readFileSync(path, "utf-8")
    if (actual !== expected) {
      throw new Error(
        [
          `${PREFIX} committed ${label} is out of date`,
          `expected committed file at ${relative(root, path)} to match the generated output`,
          `run the dev workflow to regenerate locale artifacts and commit the result`,
        ].join("\n"),
      )
    }
  }

  function assertJsonFileContents(path: string, expected: unknown, label: string) {
    if (!existsSync(path)) {
      throw new Error(`${PREFIX} missing committed ${label} at ${relative(root, path)}`)
    }

    let actual: unknown
    try {
      actual = JSON.parse(readFileSync(path, "utf-8")) as unknown
    } catch {
      throw new Error(`${PREFIX} committed ${label} is invalid JSON at ${relative(root, path)}`)
    }

    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      throw new Error(
        [
          `${PREFIX} committed ${label} is out of date`,
          `expected committed file at ${relative(root, path)} to match the generated output`,
          `run the dev workflow to regenerate locale artifacts and commit the result`,
        ].join("\n"),
      )
    }
  }

  function writeGitignore() {
    if (!usesLocalStorage) return
    const path = resolve(root, localesDir, GITIGNORE_FILENAME)
    const dir = dirname(path)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileIfChanged(path, GITIGNORE_CONTENTS)
  }

  function assertGeneratedFilesCommitted() {
    if (!usesLocalStorage) return
    assertJsonFileContents(getRuntimeConfigPath(root, localesDir), getRuntimeConfig(), "runtime config")
    assertFileContents(resolve(root, localesDir, GITIGNORE_FILENAME), GITIGNORE_CONTENTS, "generated .gitignore")
  }

  function buildLocalLocaleMessages(locale: string): RuntimeMessages {
    const existingMessages = readLocaleMessages(locale)
    const messages: RuntimeMessages = {}

    if (locale === defaultLocale) {
      for (const [id, entry] of Object.entries(manifest)) {
        messages[id] = entry.defaultMessage
      }
      return messages
    }

    for (const id of Object.keys(manifest)) {
      if (Object.hasOwn(messages, id)) continue
      if (Object.hasOwn(existingMessages, id)) {
        const existingMessage = existingMessages[id]!
        messages[id] = existingMessage
        continue
      }
      const cachedMessage = cache.entries[getCacheKey(id, locale)]?.translation
      if (cachedMessage !== undefined) messages[id] = cachedMessage
    }
    return messages
  }

  function writeLocaleFilesToDisk() {
    if (!usesLocalStorage) return
    const dir = getLocalesDirPath()
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    for (const locale of locales) {
      writeFileIfChanged(resolve(dir, `${locale}.json`), JSON.stringify(buildLocalLocaleMessages(locale), null, 2) + "\n")
    }
  }

  function getMissingMessagesByLocale() {
    const missingByLocale = new Map<string, TranslateMessage[]>()

    for (const locale of locales) {
      if (locale === defaultLocale) continue
      const existingMessages = readLocaleMessages(locale)
      for (const [id, entry] of Object.entries(manifest)) {
        if (!Object.hasOwn(existingMessages, id) && !Object.hasOwn(cache.entries, getCacheKey(id, locale))) {
          const misses = missingByLocale.get(locale) ?? []
          misses.push({
            id,
            text: entry.defaultMessage,
            meta: entry.meta,
            placeholders: entry.placeholders,
            sources: entry.sources,
          })
          missingByLocale.set(locale, misses)
        }
      }
    }

    return missingByLocale
  }

  function assertLocalBuildTranslationsComplete() {
    const expectedIds = new Set(Object.keys(manifest))
    const issues: string[] = []

    for (const locale of locales) {
      const localePath = getLocalePath(locale)
      if (!existsSync(localePath)) {
        issues.push(`- ${locale}: missing file at ${relative(root, localePath)}`)
        continue
      }

      const localeMessages = readLocaleMessages(locale)
      const missingIds = [...expectedIds].filter((id) => !Object.hasOwn(localeMessages, id))
      const orphanIds = Object.keys(localeMessages).filter((id) => !expectedIds.has(id))

      if (locale === defaultLocale) {
        const staleIds = [...expectedIds].filter((id) => localeMessages[id] !== manifest[id]!.defaultMessage)
        if (missingIds.length > 0) issues.push(formatLocaleIssue(locale, "missing", missingIds))
        if (orphanIds.length > 0) issues.push(formatLocaleIssue(locale, "orphaned", orphanIds))
        if (staleIds.length > 0) issues.push(formatLocaleIssue(locale, "outdated default messages", staleIds))
        continue
      }

      if (missingIds.length > 0) issues.push(formatLocaleIssue(locale, "missing", missingIds))
      if (orphanIds.length > 0) issues.push(formatLocaleIssue(locale, "orphaned", orphanIds))
    }

    if (issues.length === 0) return

    throw new Error(
      [
        `${PREFIX} committed locale artifacts are out of sync for local production build`,
        `local production builds are check-only and never regenerate locale files`,
        `run the dev workflow to regenerate locale artifacts and commit the result`,
        ...issues,
      ].join("\n"),
    )
  }

  async function translateMissingMessages() {
    if (!resolvedTranslate) return false
    const missingByLocale = getMissingMessagesByLocale()

    const totalMisses = [...missingByLocale.values()].reduce((count, misses) => count + misses.length, 0)
    if (totalMisses === 0) return false

    const missLocales = [...missingByLocale.keys()]
    log(
      `${PREFIX} ${BOLD}Translating${RESET} ${CYAN}${totalMisses}${RESET} ${totalMisses === 1 ? "Message" : "Messages"} -> ${CYAN}${formatLocales(missLocales)}${RESET}`,
    )

    for (const [locale, misses] of missingByLocale) {
      const result = await resolvedTranslate(misses, locale)

      for (const miss of misses) {
        const translated = result[miss.id] ?? miss.text
        cache.entries[getCacheKey(miss.id, locale)] = {
          sourceText: miss.text,
          meta: miss.meta,
          locale,
          translation: translated,
          timestamp: Date.now(),
        }
      }
    }

    return true
  }

  function scheduleDevTranslation() {
    if (!resolvedTranslate) return
    if (!isDev) return
    if (translateTimer) clearTimeout(translateTimer)
    translateTimer = setTimeout(async () => {
      const translated = await translateMissingMessages()
      if (translated) saveCache(resolve(root, cacheFile), cache)
      writeLocaleFilesToDisk()
      writePrivateManifest()
    }, 1000)
  }

  function removeFileMessages(file: string) {
    const previous = fileMessages.get(file)
    if (!previous) return false

    for (const message of previous) {
      const entry = manifest[message.id]
      if (!entry) continue
      entry.sources = entry.sources.filter((source) => !isSameSource(source, message.source))
      if (entry.sources.length === 0) delete manifest[message.id]
    }

    fileMessages.delete(file)
    return true
  }

  function syncFileMessages(file: string, messages: ExtractedMessage[]): SyncResult {
    const previousMessages = fileMessages.get(file) ?? []
    const nextEntries = groupMessagesById(messages)
    for (const [id, entry] of Object.entries(nextEntries)) {
      const existing = manifest[id]
      if (existing && !hasSameMessageShape(existing, entry)) {
        throw new Error(formatCollisionError(id, existing, entry))
      }
    }

    removeFileMessages(file)
    for (const [id, entry] of Object.entries(nextEntries)) {
      if (!manifest[id]) {
        manifest[id] = entry
        continue
      }
      for (const source of entry.sources) {
        if (!manifest[id]!.sources.some((existingSource) => isSameSource(existingSource, source))) {
          manifest[id]!.sources.push(source)
        }
      }
    }

    if (messages.length > 0) fileMessages.set(file, messages)
    return {
      manifestChanged:
        previousMessages.length !== messages.length ||
        previousMessages.some((message, index) => !isSameExtractedMessage(message, messages[index])),
      localeMessagesChanged:
        previousMessages.length !== messages.length ||
        previousMessages.some((message, index) => !hasSameMessageShape(message, messages[index]!)),
    }
  }

  function syncSourceCode(file: string, code: string) {
    const analysis = analyzeSourceFile(code, file, {
      call: CALL_MARKERS,
      component: COMPONENT_MARKERS,
      logging,
    })
    if (!analysis.parsed) return null
    return syncFileMessages(
      file,
      analysis.messages.map((message) => ({
        ...message,
        source: {
          ...message.source,
          file: toRootRelativePath(message.source.file),
        },
      })),
    )
  }

  function removeTrackedFile(file: string): SyncResult {
    const hadPreviousMessages = removeFileMessages(file)
    return {
      manifestChanged: hadPreviousMessages,
      localeMessagesChanged: hadPreviousMessages,
    }
  }

  function applySyncResult(syncResult: SyncResult | null, options: { scheduleTranslation: boolean }) {
    if (!syncResult) return
    if (syncResult.localeMessagesChanged) {
      writeLocaleFilesToDisk()
      writePrivateManifest()
      if (options.scheduleTranslation) scheduleDevTranslation()
      return
    }
    if (syncResult.manifestChanged) writePrivateManifest()
  }

  function scanAllSourceFiles() {
    for (const id of Object.keys(manifest)) delete manifest[id]
    fileMessages.clear()

    for (const sourceRoot of sourceRoots) {
      if (!existsSync(sourceRoot)) continue
      for (const file of collectScanFiles(sourceRoot).sort()) {
        const code = readFileSync(file, "utf-8")
        syncSourceCode(file, code)
      }
    }
  }

  function toRootRelativePath(file: string) {
    return relative(root, file).replaceAll("\\", "/")
  }

  function createVirtualMessagesModule() {
    if (resolvedRuntime.type === "remote") return createRemoteMessagesModule(resolvedRuntime, locales, remoteUrl)
    if (resolvedRuntime.target === "public") return createPublicMessagesModule(locales, publicBasePath)
    return createModuleMessagesModule(locales, (locale) => `/${normalizePath(toRootRelativePath(getLocalePath(locale)))}`)
  }

  return {
    name: "better-translation-extract",
    enforce: "pre",

    config() {
      return {
        ssr: {
          noExternal: ["better-translation"],
        },
      }
    },

    configResolved(config) {
      root = config.root
      isDev = config.command === "serve"
      resolvedRuntime = resolveRuntimeOptions(configuredRuntime, config)
      usesLocalStorage = resolvedRuntime.type === "local"
      localesDir = resolvedRuntime.type === "local" ? resolvedRuntime.output! : DEFAULT_LOCAL_OUTPUT_DIR
      publicBasePath =
        resolvedRuntime.type === "local" && resolvedRuntime.target === "public"
          ? (resolvedRuntime.basePath ?? DEFAULT_PUBLIC_BASE_PATH)
          : DEFAULT_PUBLIC_BASE_PATH
      remoteUrl = resolvedRuntime.type === "remote" ? (resolvedRuntime.endpoint ?? REMOTE_API_BASE_URL) : REMOTE_API_BASE_URL
      sourceRoots = (Array.isArray(rootDir) ? rootDir : [rootDir]).map((dir) => resolve(root, dir))
      log(
        `${PREFIX} Locales: ${CYAN}${formatLocales(locales)}${RESET} | Default: ${CYAN}${formatLocale(defaultLocale)}${RESET} | Runtime: ${CYAN}${formatRuntime(resolvedRuntime)}${RESET} | Out Dir: ${DIM}${usesLocalStorage ? localesDir : "n/a"}${RESET} | Roots: ${DIM}${(Array.isArray(rootDir) ? rootDir : [rootDir]).join(", ")}${RESET}`,
      )
    },

    resolveId(id) {
      if (id === VIRTUAL_MESSAGES_MODULE_ID) return RESOLVED_VIRTUAL_MESSAGES_MODULE_ID
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_MESSAGES_MODULE_ID) return createVirtualMessagesModule()
    },

    buildStart() {
      cache = loadCache(resolve(root, cacheFile))
      scanAllSourceFiles()
      if (usesLocalStorage && !isDev) {
        assertGeneratedFilesCommitted()
        assertLocalBuildTranslationsComplete()
        return
      }
      writeRuntimeConfig()
      writeGitignore()
      writeLocaleFilesToDisk()
      writePrivateManifest()

      if (isDev) scheduleDevTranslation()
    },

    configureServer(server) {
      server.watcher.add(sourceRoots)

      const syncFileFromDisk = (file: string) => {
        if (!shouldScanFile(file) || !existsSync(file)) return
        applySyncResult(syncSourceCode(file, readFileSync(file, "utf-8")), { scheduleTranslation: true })
      }

      const removeFileFromManifest = (file: string) => {
        if (!shouldScanFile(file)) return
        applySyncResult(removeTrackedFile(file), { scheduleTranslation: true })
      }

      server.watcher.on("add", syncFileFromDisk)
      server.watcher.on("change", syncFileFromDisk)
      server.watcher.on("unlink", removeFileFromManifest)
    },

    transform(code, id) {
      const cleanId = id.split("?", 1)[0] ?? id
      if (!shouldScanFile(cleanId)) return

      const analysis = analyzeSourceFile(code, cleanId, {
        call: CALL_MARKERS,
        component: COMPONENT_MARKERS,
        logging,
      })

      if (analysis.edits.length === 0) return
      return {
        code: applyEdits(code, analysis.edits),
        map: null,
      }
    },

    async generateBundle() {
      if (usesLocalStorage) {
        if (!isDev) {
          assertGeneratedFilesCommitted()
        }
        assertLocalBuildTranslationsComplete()
      } else {
        await translateMissingMessages()
      }

      if (!usesLocalStorage) {
        await syncRemote()
      }
    },

    closeBundle() {
      if (usesLocalStorage && !isDev) return
      saveCache(resolve(root, cacheFile), cache)
    },
  }
}

function formatLocaleIssue(locale: string, label: string, ids: string[]) {
  const preview = ids
    .slice(0, 5)
    .map((id) => JSON.stringify(id))
    .join(", ")
  const suffix = ids.length > 5 ? `, ... ${ids.length - 5} more` : ""
  return `- ${locale}: ${label} (${preview}${suffix})`
}

function normalizeRuntimeOptions(
  runtime: BetterTranslateRuntimeOptions | undefined,
  storage: BetterTranslateStorageOptions | undefined,
): BetterTranslateRuntimeOptions {
  if (runtime) return runtime.type === "local" ? { ...runtime, target: runtime.target ?? "module" } : runtime
  if (!storage) return { type: "local", target: "module" }
  if (storage.type === "remote") return { type: "remote", endpoint: storage.url }
  return { type: "local", target: "module", output: storage.output }
}

function resolveRuntimeOptions(runtime: BetterTranslateRuntimeOptions, config: ResolvedConfig): BetterTranslateRuntimeOptions {
  if (runtime.type === "remote") return { ...runtime, endpoint: runtime.endpoint ?? REMOTE_API_BASE_URL }

  const target = runtime.target ?? "module"
  if (target === "module") {
    return {
      ...runtime,
      target,
      output: runtime.output ?? DEFAULT_LOCAL_OUTPUT_DIR,
    }
  }

  if (!config.publicDir) {
    throw new Error(`${PREFIX} runtime target "public" requires Vite publicDir to be enabled`)
  }

  const output = runtime.output ?? normalizePath(relative(config.root, resolve(config.publicDir, DEFAULT_PUBLIC_OUTPUT_SUBDIR)))
  const outputPath = resolve(config.root, output)
  const publicBasePath = runtime.basePath ?? inferPublicBasePath(outputPath, config.publicDir)

  return {
    ...runtime,
    target,
    output,
    basePath: publicBasePath,
  }
}

function inferPublicBasePath(outputPath: string, publicDir: string) {
  const relativeToPublic = normalizePath(relative(publicDir, outputPath))
  if (relativeToPublic.startsWith("..")) {
    throw new Error(`${PREFIX} runtime target "public" output must be inside Vite publicDir unless basePath is provided`)
  }
  return `/${relativeToPublic}`.replace(/\/$/, "")
}

function formatRuntime(runtime: BetterTranslateRuntimeOptions) {
  return runtime.type === "local" ? `Local/${runtime.target ?? "module"}` : "Remote"
}

function createModuleMessagesModule(locales: string[], getImportPath: (locale: string) => string) {
  const cases = locales
    .map(
      (locale) => `    case ${JSON.stringify(locale)}:
      return (await import(${JSON.stringify(getImportPath(locale))})).default`,
    )
    .join("\n")

  return [
    `export const locales = ${JSON.stringify(locales)}`,
    "",
    "export async function loadMessages(locale) {",
    "  switch (locale) {",
    cases,
    "    default:",
    "      throw new Error(`Unknown locale: ${locale}`)",
    "  }",
    "}",
    "",
  ].join("\n")
}

function createPublicMessagesModule(locales: string[], basePath: string) {
  const normalizedBasePath = basePath.replace(/\/$/, "")
  return [
    `export const locales = ${JSON.stringify(locales)}`,
    "",
    "export async function loadMessages(locale) {",
    "  assertKnownLocale(locale)",
    `  const response = await fetch(\`${normalizedBasePath}/locales/\${encodeURIComponent(locale)}.json\`)`,
    "  if (!response.ok) throw new Error(`Failed to load locale: ${locale}`)",
    "  return response.json()",
    "}",
    "",
    createKnownLocaleAssertion(locales),
  ].join("\n")
}

function createRemoteMessagesModule(
  runtime: Extract<BetterTranslateRuntimeOptions, { type: "remote" }>,
  locales: string[],
  endpoint: string,
) {
  const normalizedEndpoint = endpoint.replace(/\/$/, "")
  const projectPath = runtime.projectId ? `/projects/${encodeURIComponent(runtime.projectId)}` : ""
  return [
    `export const locales = ${JSON.stringify(locales)}`,
    "",
    "export async function loadMessages(locale) {",
    "  assertKnownLocale(locale)",
    `  const response = await fetch(\`${normalizedEndpoint}${projectPath}/locales/\${encodeURIComponent(locale)}.json\`)`,
    "  if (!response.ok) throw new Error(`Failed to load locale: ${locale}`)",
    "  return response.json()",
    "}",
    "",
    createKnownLocaleAssertion(locales),
  ].join("\n")
}

function createKnownLocaleAssertion(locales: string[]) {
  return [
    `const knownLocales = new Set(${JSON.stringify(locales)})`,
    "",
    "function assertKnownLocale(locale) {",
    "  if (!knownLocales.has(locale)) throw new Error(`Unknown locale: ${locale}`)",
    "}",
    "",
  ].join("\n")
}

function normalizeLocaleMessages(input: unknown): RuntimeMessages {
  if (isRuntimeMessages(input)) return input
  if (
    typeof input === "object" &&
    input !== null &&
    "messages" in input &&
    typeof input.messages === "object" &&
    input.messages !== null
  ) {
    return Object.fromEntries(
      Object.entries(input.messages).flatMap(([id, entry]) =>
        typeof entry === "object" && entry !== null && "translation" in entry && typeof entry.translation === "string"
          ? [[id, entry.translation]]
          : [],
      ),
    ) as RuntimeMessages
  }
  return {}
}

function writeFileIfChanged(path: string, contents: string) {
  if (existsSync(path) && readFileSync(path, "utf-8") === contents) return false
  writeFileSync(path, contents)
  return true
}

function collectScanFiles(root: string) {
  const files: string[] = []
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = resolve(root, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === "node_modules") continue
      files.push(...collectScanFiles(path))
      continue
    }
    files.push(path)
  }
  return files
}

function isRuntimeMessages(input: unknown): input is RuntimeMessages {
  return typeof input === "object" && input !== null && Object.values(input).every((value) => typeof value === "string")
}

function applyEdits(code: string, edits: Array<{ start: number; end: number; replacement: string }>) {
  let transformed = code
  for (const edit of [...edits].sort((a, b) => b.start - a.start)) {
    transformed = `${transformed.slice(0, edit.start)}${edit.replacement}${transformed.slice(edit.end)}`
  }
  return transformed
}

function groupMessagesById(messages: ExtractedMessage[]): MessageManifest {
  const grouped: MessageManifest = {}

  for (const message of messages) {
    const existing = grouped[message.id]
    if (existing && !hasSameMessageShape(existing, message)) {
      throw new Error(formatCollisionError(message.id, existing, message))
    }
    if (!existing) {
      grouped[message.id] = {
        defaultMessage: message.defaultMessage,
        meta: message.meta,
        placeholders: message.placeholders,
        sources: [message.source],
      }
      continue
    }
    if (!existing.sources.some((source) => isSameSource(source, message.source))) {
      existing.sources.push(message.source)
    }
  }

  return grouped
}

function hasSameMessageShape(
  existing: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders">,
  incoming: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders"> | ExtractedMessage,
) {
  return (
    existing.defaultMessage === incoming.defaultMessage &&
    serializeMeta(existing.meta) === serializeMeta(incoming.meta) &&
    JSON.stringify(existing.placeholders) === JSON.stringify(incoming.placeholders)
  )
}

function isSameSource(left: MessageSource, right: MessageSource) {
  return (
    left.file === right.file &&
    left.kind === right.kind &&
    left.marker === right.marker &&
    left.start === right.start &&
    left.end === right.end
  )
}

function isSameExtractedMessage(left: ExtractedMessage, right?: ExtractedMessage) {
  if (!right) return false
  return hasSameMessageShape(left, right) && isSameSource(left.source, right.source)
}

function formatCollisionError(
  id: string,
  existing: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders" | "sources">,
  incoming: Pick<ManifestEntry, "defaultMessage" | "meta" | "placeholders" | "sources"> | ExtractedMessage,
) {
  const existingSources = formatSources(existing.sources)
  const incomingSources = formatSources("source" in incoming ? [incoming.source] : incoming.sources)
  return [
    `${PREFIX} conflicting message definition for ${BOLD}"${id}"${RESET}`,
    `existing: ${JSON.stringify({ defaultMessage: existing.defaultMessage, meta: existing.meta, placeholders: existing.placeholders })}`,
    `existing sources: ${existingSources}`,
    `incoming: ${JSON.stringify({ defaultMessage: incoming.defaultMessage, meta: incoming.meta, placeholders: incoming.placeholders })}`,
    `incoming sources: ${incomingSources}`,
  ].join("\n")
}

function formatSources(sources: MessageSource[]) {
  return sources.map((source) => `${source.file}:${source.line}:${source.column}`).join(", ")
}
